all:
  gjPositionsPlugin:
    design_elements:
#      slideshow:
#        applies_to:       [ gjPage ]                         # list the models that your design element can be used with
#        include:          [slideshow, show]                  # provide a partial 'module/action' or component [module, action] that renders this design element
#        accept:           [Image]                            # list all models that can be rendered in this design elment or ~ if none
#        params:                                              # list as many parameters as this design element needs to be configured in the admin module
#          autoplay:       { type: checkbox, default: true }  # provide a type and optionally a default value
